language: ruby
before_install: rvm get stable --without-gems=rubygems-bundler
rvm:
#  - jruby-18mode
  - jruby-19mode
#  - jruby-head
jdk:
#  - openjdk6
  - openjdk7
#  - oraclejdk7
#language: java
#install: mvn prepare-package -Dmaven.test.skip -quiet
#script: mvn cucumber:test -Djruby.versions=1.5.6
#jdk:
#  - openjdk6
#  - openjdk7
