language: ruby
bundler_args: --without copyright
rvm:
  - jruby-18mode
  - jruby-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
matrix:
  include:
    - rvm: jruby-head
      jdk: openjdk7
    - rvm: jruby
      jdk: openjdk7
      script: mvn clean verify -DskipTests
